parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - problems
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
parserOptions:
  sourceType: module
env:
  amd: true
settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .tsx
        - .js
        - .jsx
rules:
  no-console: off
  no-fallthrough: off
  no-undef-init: off
  prefer-rest-params: off
  eqeqeq: [2, "smart"]
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/ban-ts-ignore": off
  "@typescript-eslint/ban-types": off
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/no-empty-interface": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-unused-vars": [2, {vars: "all", args: "after-used", argsIgnorePattern: "^_"}]
  "@typescript-eslint/consistent-type-assertions": off
  import/order: [2, {newlines-between: "always-and-inside-groups", alphabetize: {order: "asc"}]
